 countries = {
     Afghanistan: [
         "Herat",
         "Kabul",
         "Kandahar",
         "Molah",
         "Rana",
         "Shar",
         "Sharif",
         "Wazir Akbar Khan"
     ],
     Albania: [
         "Elbasan",
         "Petran",
         "Pogradec",
         "Shkoder",
         "Tirana",
         "Ura Vajgurore"
     ],
     Algeria: [
         "Algiers",
         "Annaba",
         "Azazga",
         "Batna City",
         "Blida",
         "Bordj",
         "Bordj Bou Arreridj",
         "Bougara",
         "Cheraga",
         "Chlef",
         "Constantine",
         "Djelfa",
         "Draria",
         "El Tarf",
         "Hussein Dey",
         "Illizi",
         "Jijel",
         "Kouba",
         "Laghouat",
         "Oran",
         "Ouargla",
         "Oued Smar",
         "Relizane",
         "Rouiba",
         "Saida",
         "Souk Ahras",
         "Tamanghasset",
         "Tiaret",
         "Tissemsilt",
         "Tizi",
         "Tizi Ouzou",
         "Tlemcen"
     ],
     Bahamas: [
         "Andros Town",
         "Dunmore Town",
         "Freeport",
         "Marsh Harbour",
         "Nassau",
         "Palmetto Point",
         "Spanish Wells"
     ],
     Bahrain: [
         "Al Budayyi`",
         "Al Hadd",
         "Al Hamalah",
         "Al Janabiyah",
         "Al Markh",
         "Al Muharraq",
         "Bani Jamrah",
         "Barbar",
         "Jurdab",
         "Madinat `Isa",
         "Madinat Hamad",
         "Manama",
         "Oil City",
         "Sanabis",
         "Sanad",
         "Sitrah",
         "Tubli"
     ],
     Bangladesh: [
         "Agrabad",
         "Bangla",
         "Barisal",
         "Bazar",
         "Chittagong",
         "Comilla",
         "Delta",
         "Dhaka",
         "Hossain",
         "Jessore",
         "Kabi",
         "Kazipur",
         "Mymensingh",
         "Narayanganj",
         "Rajshahi",
         "Tejgaon",
         "Uttara"
     ],
     Barbados: [
         "Atlantic Shores",
         "Bagatelle",
         "Bloomsbury",
         "Bridgetown",
         "Bruce Vale",
         "Cave Hill",
         "Clapham",
         "Hastings",
         "Holetown",
         "Husbands",
         "Jackmans",
         "Oistins",
         "Pine Housing Estate",
         "Porters",
         "Rendezvous",
         "Rockley",
         "The Garden",
         "Wanstead",
         "Warners",
         "Warrens",
         "White Hill",
         "Wildey",
         "Worthing"
     ],
     Belize: [
         "Belize City",
         "Belmopan",
         "Benque Viejo del Carmen",
         "Freetown Sibun",
         "Ladyville",
         "San Ignacio",
         "San Pedro Town"
     ],
     Bolivia: [
         "Anillo",
         "Aroma",
         "Bermejo",
         "Caracasa",
         "Cobija",
         "Cochabamba",
         "Cotoca",
         "Cruz",
         "Guayaramerin",
         "La Paz",
         "Oruro",
         "Riberalta",
         "Santa Cruz",
         "Santa Cruz",
         "Sucre",
         "Tarija",
         "Trinidad"
     ],
     Cambodia: [
         "Moung Roessei",
         "Phnom Penh",
         "Phumi Boeng (1)",
         "Phumi Chhuk",
         "Phumi Preah Haoh",
         "Phumi Prei",
         "Phumi Prek Mrinh",
         "Phumi Siem Reab",
         "Phumi Thmei",
         "Phumi Thnal",
         "Phumi Vott Phnum",
         "Sihanoukville",
         "Tuol Kok",
         "Vott Kampong Svay"
     ],
     Cameroon: [
         "Bafia",
         "Bafoussam",
         "Bamenda",
         "Buea",
         "Douala",
         "Kribi",
         "Kumba",
         "Ringo",
         "Tibati"
     ],
     DominicanRepublic: [
         "Arenazo",
         "Bavaro",
         "Boca Chica",
         "Cabarete",
         "Cotui",
         "Dominica",
         "Guaricano",
         "Hato Mayor del Rey",
         "Jimani",
         "La Romana",
         "Los Alcarrizos",
         "Los Prados",
         "Moca",
         "Pedernales",
         "Puerto Plata",
         "Punta Cana",
         "Sabaneta",
         "San Cristobal",
         "San Fernando de Monte Cristi",
         "San Jose de Ocoa",
         "Santa Cruz de Barahona",
         "Santiago de los Caballeros",
         "Santo Domingo"
     ],
     ElSalvador: [
         "Ahuachapan",
         "Antiguo Cuscatlan",
         "Apaneca",
         "Apopa",
         "Ayutuxtepeque",
         "Botoncillal El Botoncillo",
         "Coatepeque",
         "Colon",
         "Colonia Escalon",
         "Cuscatancingo",
         "Delgado",
         "Gigante",
         "Guazapa",
         "Ilopango",
         "La Libertad",
         "Lourdes",
         "Mejicanos",
         "Nuevo Cuscatlan",
         "Ozatlan",
         "San Jose Villanueva",
         "San Marcos",
         "San Miguel",
         "San Salvador",
         "Santa Ana",
         "Santa Tecla",
         "Santiago Texacuangos",
         "Sonsonate",
         "Soyapango",
         "Usulutan",
         "Zaragoza"
     ],
     Estonia: [
         "Aasmae",
         "Aaviku",
         "Aespa",
         "Ahtma",
         "Alliku",
         "Ambla",
         "Antsla",
         "Ardu",
         "Avinurme",
         "Elva",
         "Emmaste",
         "Haabneeme",
         "Haage",
         "Haapsalu",
         "Halinga",
         "Harju",
         "Harku",
         "Kaarma",
         "Kadrina",
         "Kehra",
         "Keila",
         "Kiili",
         "Kohila",
         "Kohtla",
         "Kose",
         "Kulna",
         "Kuressaare",
         "Kuusalu",
         "Laagri",
         "Lagedi",
         "Lahtse",
         "Lepna",
         "Loksa",
         "Loo",
         "Lubja",
         "Maardu",
         "Muraste",
         "Narva",
         "Otepaeae",
         "Paide",
         "Paikuse",
         "Paldiski",
         "Palivere",
         "Peetri",
         "Puhja",
         "Rakke",
         "Rakvere",
         "Rapla",
         "Saku",
         "Saue",
         "Sindi",
         "Somerpalu",
         "Syare",
         "Tabasalu",
         "Tabivere",
         "Tallinn",
         "Tamsalu",
         "Tapa",
         "Tartu",
         "Toila",
         "Vaida",
         "Valga",
         "Vara",
         "Venevere",
         "Viimsi",
         "Viljandi",
         "Voka"
     ]
 };


 for (i = 0; i <= countries.length; i++) {

     console.log(i)
 }